// Static trader geolocation data
// This file contains pre-mapped traders with their coordinates

export interface MappedTrader {
  address: string;
  displayName: string;
  avatar: string;
  tier: 'S' | 'A' | 'B' | 'C' | 'D' | 'E';
  xUsername?: string;
  latitude: number;
  longitude: number;
  country: string;
  totalPnl: number;
  winRate: number;
  rarityScore: number;
}

// Country coordinates
const COUNTRY_COORDS: Record<string, { lat: number; lon: number }> = {
  'Germany': { lat: 51.1657, lon: 10.4515 },
  'Europe': { lat: 50.0, lon: 10.0 },
  'Brazil': { lat: -14.2350, lon: -51.9253 },
  'Italy': { lat: 41.8719, lon: 12.5674 },
  'East Asia & Pacific': { lat: 35.0, lon: 105.0 },
  'United States': { lat: 37.0902, lon: -95.7129 },
  'Spain': { lat: 40.4637, lon: -3.7492 },
  'Australasia': { lat: -25.0, lon: 135.0 },
  'Australia': { lat: -25.2744, lon: 133.7751 },
  'Hong Kong': { lat: 22.3193, lon: 114.1694 },
  'United Kingdom': { lat: 55.3781, lon: -3.4360 },
  'Korea': { lat: 37.5665, lon: 126.9780 },
  'Japan': { lat: 36.2048, lon: 138.2529 },
  'Lithuania': { lat: 55.1694, lon: 23.8813 },
  'Canada': { lat: 56.1304, lon: -106.3468 },
  'Denmark': { lat: 56.2639, lon: 9.5018 },
  'Thailand': { lat: 15.8700, lon: 100.9925 },
  'Slovakia': { lat: 48.6690, lon: 19.6990 },
  'Morocco': { lat: 31.7917, lon: -7.0926 },
  'Estonia': { lat: 58.5953, lon: 25.0136 },
  'Turkey': { lat: 38.9637, lon: 35.2433 },
  'Indonesia': { lat: -0.7893, lon: 113.9213 },
  'West Asia': { lat: 29.0, lon: 53.0 },
  'Poland': { lat: 51.9194, lon: 19.1451 },
  'Austria': { lat: 47.5162, lon: 14.5501 },
  'North America': { lat: 54.5260, lon: -105.2551 },
  'Netherlands': { lat: 52.1326, lon: 5.2913 },
  'Ireland': { lat: 53.4129, lon: -8.2439 },
  'New Zealand': { lat: -40.9006, lon: 174.8860 },
  'Sweden': { lat: 60.1282, lon: 18.6435 },
  'Ecuador': { lat: -1.8312, lon: -78.1834 },
  'Singapore': { lat: 1.3521, lon: 103.8198 },
  'Uzbekistan': { lat: 41.3775, lon: 64.5853 },
  'United Arab Emirates': { lat: 23.4241, lon: 53.8478 },
  'Ukraine': { lat: 48.3794, lon: 31.1656 },
  'Czech Republic': { lat: 49.8175, lon: 15.4730 },
  'Taiwan': { lat: 23.6978, lon: 120.9605 },
  'Eastern Europe (Non-EU)': { lat: 50.0, lon: 30.0 },
  'France': { lat: 46.2276, lon: 2.2137 },
  'Argentina': { lat: -38.4161, lon: -63.6167 },
  'South Asia': { lat: 20.0, lon: 78.0 },
  'India': { lat: 20.5937, lon: 78.9629 },
  'Croatia': { lat: 45.1, lon: 15.2 },
};

// Twitter username → location mapping
const TRADER_LOCATIONS: Record<string, { country: string; displayName: string; tier: 'S' | 'A' | 'B' }> = {
  // Original list
  '0xTactic': { country: 'Germany', displayName: 'Tactic', tier: 'S' },
  '0xTrinity': { country: 'Europe', displayName: '0xTrinity.eth', tier: 'S' },
  'AbrahamKurland': { country: 'Brazil', displayName: 'Abe Kurland', tier: 'S' },
  'AnjunPoly': { country: 'Italy', displayName: 'Anjun', tier: 'S' },
  'AnselFang': { country: 'East Asia & Pacific', displayName: '孤狼资本', tier: 'S' },
  'BeneGesseritPM': { country: 'United States', displayName: 'BeneGesseritVoice', tier: 'S' },
  'Betwick1': { country: 'Spain', displayName: 'Betwick', tier: 'S' },
  'BitalikWuterin': { country: 'Australasia', displayName: 'manan', tier: 'S' },
  'BrokieTrades': { country: 'United States', displayName: 'brokie', tier: 'S' },
  'CUTNPASTE4': { country: 'Australia', displayName: 'CUTNPASTE', tier: 'S' },
  'Cabronidus': { country: 'Spain', displayName: 'Omuss.hl (THE GOAT)', tier: 'S' },
  'CarOnPolymarket': { country: 'Europe', displayName: 'Car', tier: 'S' },
  'ColeBartiromo': { country: 'United States', displayName: 'Cole Bartiromo', tier: 'S' },
  'Domahhhh': { country: 'Ireland', displayName: 'Domer', tier: 'S' },
  'Dyor_0x': { country: 'United Kingdom', displayName: 'DYOR.eth', tier: 'S' },
  'Eltonma': { country: 'Hong Kong', displayName: 'Elton Ma', tier: 'S' },
  'EricZhu06': { country: 'United States', displayName: 'Eric Zhu', tier: 'S' },
  'Ferzinhagianola': { country: 'United Kingdom', displayName: 'gabriella fernanda', tier: 'A' },
  'Foster': { country: 'United States', displayName: 'Foster', tier: 'S' },
  'HanRiverVictim': { country: 'Korea', displayName: 'JM', tier: 'A' },
  'HarveyMackinto2': { country: 'Japan', displayName: 'YatSen', tier: 'A' },
  'IceFrosst': { country: 'Lithuania', displayName: 'IceFrost.base.eth', tier: 'A' },
  'Impij25': { country: 'Canada', displayName: 'Padda', tier: 'A' },
  'IqDegen': { country: 'Germany', displayName: 'IQ=degen', tier: 'A' },
  'JJo3999': { country: 'Australia', displayName: 'JJo', tier: 'A' },
  'Junk3383': { country: 'Korea', displayName: 'christophe de cuijpe', tier: 'A' },
  'LegenTrader86': { country: 'Hong Kong', displayName: 'DimSumboiiiiiiiii', tier: 'A' },
  'MiSTkyGo': { country: 'Europe', displayName: 'MisTKy', tier: 'S' },
  'MrOziPM': { country: 'Denmark', displayName: 'mr.ozi', tier: 'A' },
  'ParkDae_gangnam': { country: 'Thailand', displayName: 'Dit_s', tier: 'A' },
  'PatroclusPoly': { country: 'Canada', displayName: 'Patroclus', tier: 'A' },
  'SnoorrrasonPoly': { country: 'Slovakia', displayName: 'Snoorrason', tier: 'A' },
  'UjxTCY7Z7ftjiNq': { country: 'Korea', displayName: 'SynapseAlpha.eth', tier: 'S' },
  'XPredicter': { country: 'Morocco', displayName: 'X', tier: 'A' },
  'biancalianne418': { country: 'Japan', displayName: 'Bianca', tier: 'A' },
  'bitcoinzhang1': { country: 'Japan', displayName: '马踢橘子', tier: 'A' },
  'cripes3': { country: 'Spain', displayName: 'too eazy1', tier: 'B' },
  'cynical_reason': { country: 'Estonia', displayName: 'sigh', tier: 'B' },
  'debased_PM': { country: 'Turkey', displayName: 'debased', tier: 'B' },
  'denizz_poly': { country: 'Indonesia', displayName: 'denizz', tier: 'B' },
  'drewlivanos': { country: 'United States', displayName: 'drew', tier: 'A' },
  'dw8998': { country: 'East Asia & Pacific', displayName: 'David', tier: 'A' },
  'evan_semet': { country: 'United States', displayName: 'Thanos Chad', tier: 'S' },
  'feverpromotions': { country: 'Japan', displayName: 'Fever Promotions', tier: 'B' },
  'fortaellinger': { country: 'West Asia', displayName: 'stone cold ape', tier: 'B' },
  'holy_moses7': { country: 'West Asia', displayName: 'Moses', tier: 'B' },
  'hypsterlo': { country: 'Poland', displayName: 'hypsterlo', tier: 'B' },
  'johnleftman': { country: 'United States', displayName: 'John Leftman', tier: 'A' },
  'jongpatori': { country: 'Korea', displayName: 'donjo', tier: 'B' },
  'joselebetis2': { country: 'Australia', displayName: 'josele.sol', tier: 'B' },
  'love_u_4ever': { country: 'Hong Kong', displayName: '0xp3nny', tier: 'B' },
  'one8tyfive': { country: 'Austria', displayName: 'Dominikas S.', tier: 'A' },
  'smdx_btc': { country: 'United States', displayName: 'Magics', tier: 'A' },
  'tulipking': { country: 'North America', displayName: 'Tulip King', tier: 'A' },
  'vacoolaaaa': { country: 'Netherlands', displayName: 'vacoola', tier: 'B' },
  'videlake': { country: 'Hong Kong', displayName: 'Teribleble', tier: 'B' },
  'wkmfa57': { country: 'Hong Kong', displayName: 'wkmfa57', tier: 'B' },
  
  // New batch
  '0x8dxd': { country: 'New Zealand', displayName: '0x8dxd', tier: 'S' },
  'Nooserac': { country: 'Canada', displayName: 'Nooserac', tier: 'S' },
  'tupac_poly': { country: 'United States', displayName: 'tupac_poly', tier: 'S' },
  'DigAssets01': { country: 'United States', displayName: 'DigAssets01', tier: 'S' },
  'Iridium1911': { country: 'Japan', displayName: 'Iridium1911', tier: 'S' },
  'MisTky007': { country: 'Sweden', displayName: 'MisTky007', tier: 'S' },
  'ka_wa_wa': { country: 'Canada', displayName: 'ka_wa_wa', tier: 'S' },
  'Parz1valPM': { country: 'Europe', displayName: 'Parz1valPM', tier: 'S' },
  'ThePrexpect': { country: 'East Asia & Pacific', displayName: 'ThePrexpect', tier: 'S' },
  'yonezyb': { country: 'Ecuador', displayName: 'yonezyb', tier: 'A' },
  'UjxTCYZZftijNq': { country: 'Korea', displayName: 'UjxTCYZZftijNq', tier: 'S' },
  'Jesterthegoose': { country: 'North America', displayName: 'Jesterthegoose', tier: 'A' },
  'imdatn_': { country: 'Spain', displayName: 'imdatn_', tier: 'A' },
  'JustinClaborn1': { country: 'Hong Kong', displayName: 'JustinClaborn1', tier: 'S' },
  'DespinaWade9': { country: 'Hong Kong', displayName: 'DespinaWade9', tier: 'A' },
  'mm_legitimate': { country: 'United States', displayName: 'mm_legitimate', tier: 'S' },
  'Dropper': { country: 'Brazil', displayName: 'Dropper', tier: 'A' },
  'Nanavo': { country: 'Brazil', displayName: 'Nanavo', tier: 'A' },
  'Euan': { country: 'Europe', displayName: 'Euan', tier: 'A' },
  'Macaco': { country: 'United States', displayName: 'Macaco', tier: 'S' },
  'ThanosChad': { country: 'United States', displayName: 'ThanosChad', tier: 'S' },
  'HazelProvencal': { country: 'Hong Kong', displayName: 'HazelProvencal', tier: 'A' },
  'MEPP': { country: 'Canada', displayName: 'MEPP', tier: 'A' },
  'Scottilicious': { country: 'Hong Kong', displayName: 'Scottilicious', tier: 'A' },
  'ascetic': { country: 'North America', displayName: 'ascetic', tier: 'A' },
  'coinlaundry': { country: 'United Arab Emirates', displayName: 'coinlaundry', tier: 'A' },
  'Fridge': { country: 'Europe', displayName: 'Fridge', tier: 'A' },
  'thanksforshow_': { country: 'Netherlands', displayName: 'thanksforshow_', tier: 'A' },
  'Viter': { country: 'Ukraine', displayName: 'Viter', tier: 'A' },
  'Jahoda': { country: 'Czech Republic', displayName: 'Jahoda', tier: 'A' },
  'BagCalls': { country: 'North America', displayName: 'BagCalls', tier: 'A' },
  'Gr0wCrypt0': { country: 'United States', displayName: 'Gr0wCrypt0', tier: 'A' },
  'bhuo188': { country: 'Taiwan', displayName: 'bhuo188', tier: 'A' },
  'MonteCarloSpam': { country: 'Netherlands', displayName: 'MonteCarloSpam', tier: 'A' },
  'tsybka': { country: 'Eastern Europe (Non-EU)', displayName: 'tsybka', tier: 'B' },
  'Tenebrus87': { country: 'Germany', displayName: 'Tenebrus87', tier: 'A' },
  'XPredictor': { country: 'Morocco', displayName: 'XPredictor', tier: 'A' },
  'MassimoDelfini': { country: 'Spain', displayName: 'MassimoDelfini', tier: 'A' },
  'Purebet_io': { country: 'Europe', displayName: 'Purebet_io', tier: 'B' },
  'GohstPM': { country: 'Netherlands', displayName: 'GohstPM', tier: 'A' },
  'world_blocks': { country: 'Netherlands', displayName: 'world_blocks', tier: 'A' },
  'Nihaww_': { country: 'France', displayName: 'Nihaww_', tier: 'A' },
  'Frank3261939249': { country: 'Hong Kong', displayName: 'Frank3261939249', tier: 'B' },
  'elucidxte': { country: 'Australia', displayName: 'elucidxte', tier: 'A' },
  'alesia_kod96360': { country: 'Japan', displayName: 'alesia_kod96360', tier: 'B' },
  'tenad0me': { country: 'North America', displayName: 'tenad0me', tier: 'A' },
  'dontoverfit': { country: 'Brazil', displayName: 'dontoverfit', tier: 'A' },
  'ebobc_eth': { country: 'Argentina', displayName: 'ebobc_eth', tier: 'A' },
  'TheWolfOfPoly': { country: 'Europe', displayName: 'TheWolfOfPoly', tier: 'A' },
  'traderman222': { country: 'Czech Republic', displayName: 'traderman222', tier: 'A' },
  'Peregrine_u': { country: 'Japan', displayName: 'Peregrine_u', tier: 'A' },
  'netrol_': { country: 'Italy', displayName: 'netrol_', tier: 'A' },
  'polyfirefly': { country: 'South Asia', displayName: 'polyfirefly', tier: 'B' },
  'samoHypebears': { country: 'Ukraine', displayName: 'samoHypebears', tier: 'A' },
  'Impi25': { country: 'Canada', displayName: 'Impi25', tier: 'A' },
  'DuraskinP': { country: 'Hong Kong', displayName: 'DuraskinP', tier: 'B' },
  'NestorK67460812': { country: 'Hong Kong', displayName: 'NestorK67460812', tier: 'B' },
  'baiyunhea': { country: 'Hong Kong', displayName: 'baiyunhea', tier: 'B' },
  'pr1nas': { country: 'Brazil', displayName: 'pr1nas', tier: 'A' },
  'Zalbeeeeeeeeng': { country: 'Ireland', displayName: 'Zalbeeeeeeeeng', tier: 'A' },
  'rlverside0': { country: 'Japan', displayName: 'rlverside0', tier: 'B' },
  'wuestenigel': { country: 'Germany', displayName: 'wuestenigel', tier: 'A' },
  'PredictaDamusX': { country: 'United Kingdom', displayName: 'PredictaDamusX', tier: 'A' },
  'seems1126': { country: 'Japan', displayName: 'seems1126', tier: 'B' },
  'nicoco89poly': { country: 'Europe', displayName: 'nicoco89poly', tier: 'B' },
  'HollandKatyoann': { country: 'Ukraine', displayName: 'HollandKatyoann', tier: 'B' },
  'AlisaFox56572': { country: 'Hong Kong', displayName: 'AlisaFox56572', tier: 'B' },
  'zmzweb3': { country: 'Japan', displayName: 'zmzweb3', tier: 'B' },
  'Joker_Poly': { country: 'Canada', displayName: 'Joker_Poly', tier: 'A' },
  'arun_14159': { country: 'India', displayName: 'arun_14159', tier: 'A' },
  'ferrellcode': { country: 'United States', displayName: 'ferrellcode', tier: 'A' },
  'VespucciPM': { country: 'Europe', displayName: 'VespucciPM', tier: 'A' },
  'sherogog': { country: 'Austria', displayName: 'sherogog', tier: 'A' },
  'guhhhtradez': { country: 'Croatia', displayName: 'guhhhtradez', tier: 'B' },
};

// Generate static traders with coordinates
export const STATIC_MAPPED_TRADERS: MappedTrader[] = Object.entries(TRADER_LOCATIONS).map(([xUsername, data]) => {
  const coords = COUNTRY_COORDS[data.country];
  
  // Add small random offset to avoid exact overlap
  const latOffset = (Math.random() - 0.5) * 2;
  const lonOffset = (Math.random() - 0.5) * 2;
  
  // Generate fake address based on username
  const fakeAddress = `0x${xUsername.slice(0, 8).padEnd(40, '0')}`;
  
  return {
    address: fakeAddress,
    displayName: data.displayName,
    avatar: `https://unavatar.io/twitter/${xUsername}`,
    tier: data.tier,
    xUsername,
    latitude: coords.lat + latOffset,
    longitude: coords.lon + lonOffset,
    country: data.country,
    totalPnl: data.tier === 'S' ? 100000 : data.tier === 'A' ? 50000 : 25000,
    winRate: data.tier === 'S' ? 0.65 : data.tier === 'A' ? 0.58 : 0.52,
    rarityScore: data.tier === 'S' ? 80000 : data.tier === 'A' ? 60000 : 40000,
  };
});
